version: "3.9"
services:
  fastapi-ylab:
    container_name: ylab_api

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - "DATABASE_URL:${DATABASE_URL}"

    volumes:
      - ./:/app

    entrypoint: >
      sh -c "
        alembic upgrade head &&
        uvicorn src.main:app --host 0.0.0.0 --reload
      "
    ports:
      - "8000:8000"
    networks:
      - ylab_network
    depends_on:
      ylab_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    # restart: always

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - ylab_network

  rabbitmq:
    image: rabbitmq:3.12.2-management-alpine
    container_name: rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_HEALTH_CHECK_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_HEALTH_CHECK_PASSWORD: ${RABBITMQ_PASSWORD}

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s

    ports:
      - 15672:15672
      - 5672:5672

    networks:
      - ylab_network

  celery_worker:
    build: .
    entrypoint: celery -A src.celery.celery_worker:celery worker --beat --loglevel=info
    depends_on:
      - rabbitmq
      - fastapi-ylab
    networks:
      - ylab_network
    volumes:
      - ./:/app

  ylab_db:
    image: postgres:15.1-alpine
    container_name: ylab_db
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGUSER: "${PGUSER}"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${PGUSER}", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - ylab_network

networks:
  ylab_network:
    name: ylab_network
volumes:
  postgres_data:
  cache:
