"""alter dish price column

Revision ID: 43132aff5949
Revises: ab0e55b08969
Create Date: 2023-07-23 13:17:07.016391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43132aff5949'
down_revision = 'ab0e55b08969'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
