"""alter dish price column

Revision ID: ab0e55b08969
Revises: f7ccff2200a8
Create Date: 2023-07-23 13:15:49.405280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0e55b08969'
down_revision = 'f7ccff2200a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
